import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google"
// import Slidebar from "@/components/Sidebar";
// import Header from "@/components/Header";


const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex justify-between items-start`}
      >
        {/* <Slidebar /> */}
        {/* <main className="grid w-full h-full pl-[300px]">
          <Header />
          
        </main> */}
        {children}
      </body>
    </html>
  );
}
